{
 "title": "Netology",
 "time": { "from": "2026-06-10T12:44:53.290Z", "to": "2026-06-10T12:53:59.478Z" },
 "panels": [
  {
   "title": " CPU LA 1/5/15 (Load Average)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Утилизация CPU (в процентах, 100 - idle)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе (свободное место в байтах)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти (гигабайтах)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}